[from-internal]

exten => 1000,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => _300[3-4],1,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

exten => _300[1-2],1,Dial(PJSIP/${EXTEN}@kamailio,30)
 same => n,Hangup()
